services:
  - type: web
    name: Paxly-Lite
    runtime: docker
    rootDir: backend
    branch: api-refactor
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PORT
        value: 10000
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: ENCRYPTION_KEY
        sync: false
      - key: STORAGE_MODE
        value: local
      - key: BACKEND_URL
        value: https://paxly-lite.onrender.com
      - key: FRONTEND_URL
        value: https://paxly-lite.vercel.app
